INSERT INTO public.genre_model ("name") VALUES('ecchi');
INSERT INTO public.genre_model ("name") VALUES('romance');
INSERT INTO public.genre_model ("name") VALUES('isekai');
INSERT INTO public.genre_model ("name") VALUES('action');
INSERT INTO public.genre_model ("name") VALUES('adventure');
INSERT INTO public.genre_model ("name") VALUES('comedy');
INSERT INTO public.genre_model ("name") VALUES('drama');
INSERT INTO public.genre_model ("name") VALUES('slice of life');
INSERT INTO public.genre_model ("name") VALUES('fantasy');
INSERT INTO public.genre_model ("name") VALUES('magic');
INSERT INTO public.genre_model ("name") VALUES('supernatural');
INSERT INTO public.genre_model ("name") VALUES('horror');
INSERT INTO public.genre_model ("name") VALUES('mystery');
INSERT INTO public.genre_model ("name") VALUES('psychological');
INSERT INTO public.genre_model ("name") VALUES('sci-fi');
INSERT INTO public.genre_model ("name") VALUES('cyberpunk');
INSERT INTO public.genre_model ("name") VALUES('game');
INSERT INTO public.genre_model ("name") VALUES('demons');
INSERT INTO public.genre_model ("name") VALUES('harem');
INSERT INTO public.genre_model ("name") VALUES('josei');
INSERT INTO public.genre_model ("name") VALUES('martial arts');
INSERT INTO public.genre_model ("name") VALUES('kids');
INSERT INTO public.genre_model ("name") VALUES('historical');
INSERT INTO public.genre_model ("name") VALUES('hentai');
INSERT INTO public.genre_model ("name") VALUES('military');
INSERT INTO public.genre_model ("name") VALUES('mecha');
INSERT INTO public.genre_model ("name") VALUES('parody');
INSERT INTO public.genre_model ("name") VALUES('music');
INSERT INTO public.genre_model ("name") VALUES('police');
INSERT INTO public.genre_model ("name") VALUES('post-apocalyptic');
INSERT INTO public.genre_model ("name") VALUES('reverse harem');
INSERT INTO public.genre_model ("name") VALUES('school');
INSERT INTO public.genre_model ("name") VALUES('seinen');
INSERT INTO public.genre_model ("name") VALUES('shoujo');
INSERT INTO public.genre_model ("name") VALUES('shounen');
INSERT INTO public.genre_model ("name") VALUES('space');
INSERT INTO public.genre_model ("name") VALUES('sports');
INSERT INTO public.genre_model ("name") VALUES('super power');
INSERT INTO public.genre_model ("name") VALUES('tragedy');
INSERT INTO public.genre_model ("name") VALUES('vampire');
INSERT INTO public.genre_model ("name") VALUES('yuri');
INSERT INTO public.genre_model ("name") VALUES('doujin');
